### ISSUE TITLE
Generate Token under Token management API of swagger doesn’t work in first request.

### ISSUE THREAD

**Issue by nirmalchief** [phaneesh/primer#1]
Hi Phaneesh,
Have below issue..

Generate Token under Token management API of swagger doesn’t work in first request.It gives error in first request. In 2nd request onwards it generates the Token.
It gives me the error message as below of -

{
  "errorCode": "PR000",
  "message": "Observable onError"
}
 I kept the as below-
AEROSPIKE_TIMEOUT=300000

Any opinion ?

**Comment by phaneesh** [comment]
@nirmalchief Is is only through swagger or even calling the api using curl/any other client also fails ?

**Comment by phaneesh** [comment]
@nirmalchief I have tried it numerous times. I am unable to reproduce the issue.

**Comment by nirmalchief** [comment]
Tried with swagger as well as client code and both places we notice this issue..
