### ISSUE TITLE
How to configure primer with external zookeepr?

### ISSUE THREAD

**Issue by nirmalchief** [phaneesh/primer#2]
Hi Phaneesh,

How can we configure primer with external zookeeper? Earlier we were able to run it with our zookeeper ,but with your latest changes it is automatically downloading the zookeeper and starting it. So we are not able to configure with our zookeeper ?

Any opinion ? Please suggest?

**Comment by phaneesh** [comment]
@nirmalchief Zookeeper dependency has been removed. It is no longer required to run primer
