### ISSUE TITLE
How can we start swagger on different port other than 8080?

### ISSUE THREAD

**Issue by nirmalchief** [phaneesh/primer#4]
Where all I need to change to start it on port other than 8080?

**Comment by phaneesh** [comment]
@nirmalchief Swagger always starts on application port. However you can disable it by changing the configuration

**Comment by nirmalchief** [comment]
Tried changing the port in docker-compose.yml, primer/config/dev/config.yml and primer/config/docker/config.yml but didn't worked for me.Can you please help me to know which config i missed or where exactly i have to change the config to access the api from different port..
